# -*- coding: utf-8 -*-
"""Firsrt code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111MyvSYH8wAoRePX5lELhQr4FUHszsVF
"""

LEven=[2,4,6,8,10]
LOdd=[1,3,5,7,9]

LSum=[]
LMulti=[]
LAngle=[]
LAngle=[a for a in range(0,361,30)]
 
  
print(LAngle)
i1=LAngle.index(90)
i2=LAngle.index(270)
print(i1)
print(i2)

i1_rev=i1-len(LAngle)
i2_rev=i2-len(LAngle)

print(i1_rev)
print(i2_rev)
Lrev=[]

Lrev=LAngle[i2_rev:i1_rev-1:-1]


print(Lrev)





l1=[2,4,6,8,10]
l2=l1
del l2[3]
print(l1)

l3=l1.copy()

del l3[3]

print(l1)
print(l3)

import numpy as np
import tensorflow as tf


dir(np)

tupl1=(1,2,3)
tupl2=(7,8)
tupl1=tupl1*3




print(tupl1)

states={'Andra pradesh':[48900980,'Hyderbad',False],'Karnataka':[67086786,'Bangalore',True],'TamilNadu':[645464574,'Chennai',False],'Bihar':[6457657,'patna',True]}

states['Telangana']=[46546754,'Hyderbad',True]
print(states)

def deg_rad(angle):
  return angle*22/7/180

def rad_deg(rad):
  return 180*7*rad/22

x=lambda angle,rotate:angle/180*22/7+rotate

y=x(30,deg_rad(90))
print(y)

print(rad_deg(y))